# Generated by Django 4.0.4 on 2022-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.CharField(max_length=20, verbose_name='额度')),
                ('token', models.CharField(max_length=50, verbose_name='卡密')),
            ],
            options={
                'db_table': 'carmy',
            },
        ),
        migrations.CreateModel(
            name='IP1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip')),
                ('post', models.CharField(max_length=20, verbose_name='端口')),
            ],
            options={
                'db_table': 'IP1',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('quantity', models.CharField(max_length=20, verbose_name='剩余数量')),
                ('qq', models.CharField(max_length=20, verbose_name='qq号')),
                ('security', models.CharField(max_length=20, verbose_name='密保')),
                ('creation_date', models.DateField()),
                ('recent_login', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
